Remove some default associated types, so that default methods don’t have to be overridden.
Since https://github.com/rust-lang/rust/pull/26728 , Servo would get build errors like:

    error: the following trait items need to be reimplemented as `AtRule` was overridden: `rule_without_block` [E0399]
        type AtRule = CSSRule;
        ^~~~~~~~~~~~~~~~~~~~~~